# Generated by Django 4.2.2 on 2023-07-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eDiary', '0004_noteshistory_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='drawing',
            field=models.ImageField(null=True, upload_to='drawings/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobileNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
