# Generated by Django 4.2.2 on 2023-07-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eDiary', '0005_drawing_notes_drawing_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.ImageField(null=True, upload_to='signup_images/'),
        ),
    ]
