# Generated by Django 4.2.2 on 2023-07-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eDiary', '0006_notes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='image',
        ),
    ]
