# Generated by Django 4.2.2 on 2023-08-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eDiary', '0007_uploadimage_remove_notes_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AlterField(
            model_name='notes',
            name='drawing',
            field=models.ImageField(null=True, upload_to='media/drawings/'),
        ),
    ]
